@TicTacToe_RESTAPI_HostAddress = http://localhost:32769

GET {{TicTacToe_RESTAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{TicTacToe_RESTAPI_HostAddress}}/test/
Accept: application/json

